config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'categories#index'

  resources :categories do
    resources :lists do
      resources :items
    end
  end

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  belongs_to :user
  has_many :lists, dependent: :destroy
  validates :title, presence: true, uniqueness: true
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  list_id    :integer
#

class Item < ActiveRecord::Base
  belongs_to :list
  validates :content, presence: true
end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  title       :string
#  category_id :integer
#

class List < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :items, dependent: :destroy
  validates :title, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :categories, dependent: :destroy
  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def index
    @categories = current_user.categories
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to root_path
  end

  private

    def category_params
      params.require(:category).permit(:title)
    end

    def find_category
      @category = Category.find(params[:id])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_list
  before_action :find_category

  def create
    @item = @list.items.create(item_params)

    if @item.save
      redirect_to category_list_path(@category, @list)
    else
      redirect_to(:back)
    end
  end

  def destroy
    @item = @list.items.find(params[:id])
    @item.destroy
    redirect_to category_list_path(@category, @list) 
  end

  private

    def item_params
      params.require(:item).permit(:content)
    end

    def find_category
      @category = Category.find(params[:category_id])
    end

    def find_list
      @list = List.find(params[:list_id])
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_category
  before_action :find_list, except: [:new, :create]
  before_action :authenticate_user!

  def new
    @list = List.new
  end

  def create
    @list = @category.lists.create(list_params)

    if @list.save
      redirect_to category_list_path(@category, @list)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @list.destroy
    redirect_to category_path(@category)
  end

  private

    def list_params
      params.require(:list).permit(:title, :description)
    end

    def find_category
      @category = Category.find(params[:category_id])
    end

    def find_list
      @list = List.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>

  <%= f.submit "Submit" %>
<% end %>

app/views/categories/destroy.html.erb
<h1>Category#destroy</h1>
<p>Find me in app/views/category/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to "Cancel", root_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% @categories.each do |category| %>
  <ul class="list-group">
    <li class="list-group-item">
      <%= link_to category.title, category %>
      <%= link_to "Edit", edit_category_path(category), class: "btn btn-default" %>
      <%= link_to "Delete", category, method: :delete, data: { confirm: "Delete this category?" }, class: "btn btn-default" %>
    </li>
  </ul>
<% end %>

<%= link_to "New Category", new_category_path, class: "btn btn-primary" %>

<h2>Priority</h2>

<div id="priorities">
  <% Item.all.each do |item| %>
    <p><%= item.content if item.priority == true %></p>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

  <%= render @category.lists %>
 
  <%= link_to "New List", new_category_list_path(@category), class: "btn btn-primary" %>

app/views/categories/update.html.erb
<h1>Category#update</h1>
<p>Find me in app/views/category/update.html.erb</p>

app/views/items/_form.html.erb
<%= form_for([@category, @list, @list.items.build]) do |f| %>
  <%= f.text_field :content %>

  <%= f.submit "Submit" %>
<% end %>

app/views/items/_item.html.erb
<ul>
  <li>
    <%= item.content %>
    <%= link_to "Complete", category_list_item_path(@category, @list, item), method: :delete, data: { confirm: "Delete this item?" } %>
    <%= link_to "Add to priority list", "#" if item.priority == false %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Productify</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-inverse">
        <div class="container">
          <ul class="nav nav-pills">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: {confirm: "Sign Out?"} %></li>
          </ul>
        </div>
      </nav>
    <header>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>

app/views/lists/_form.html.erb
<%= form_for([@category, @list]) do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>

  <%= f.label "Description" %>
  <%= f.text_field :description%>

  <%= f.submit "Submit" %>
<% end %>

app/views/lists/_list.html.erb
<ul class="list-group"> <li class="list-group-item">
    <%= link_to list.title, category_list_path(@category, list) %>
    <%= link_to "Edit", edit_category_list_path(@category, list), class: "btn btn-default" %>
    <%= link_to "Delete", category_list_path(@category, list), class: "btn btn-default", method: :delete, data: { confirm: "Delete this category?" } %>
  </li>
  <p><%= list.description %></p>
</ul>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render 'form' %>

<%= link_to "Cancel", category_path(@category) %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<% @lists.each do |list| %>
  <%= link_to list.title, list %>
<% end %>
  

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to "Back", category_path(@category) %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>
<h1><%= @list.description %></h1>
 
  <%= render @list.items %>
  <%= render 'items/form' %>

  <%= link_to "Back", category_path(@category) %>